<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Modern, comprehensive quality manag_7efc63</name>
   <tag></tag>
   <elementGuidId>47016d09-b90b-4b73-b18d-a07d949b90c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.hero_section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>ab696ca1-4fc1-4e20-a8b3-de9d537c37b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero_section</value>
      <webElementGuid>8204456d-85ca-4940-8592-265633e00cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>10a19626-3d22-46b6-ba81-ec109cb0fdbd</value>
      <webElementGuid>41d5bda1-36a8-4d9a-b901-4160278e2576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modern, comprehensive quality management platformDeliver world-class digital experiences with an AI-augmented platform that lets you plan, author and execute automated tests.Get startedView a demoHelping 30K+ software, DevOps and quality teams test and launch software faster.</value>
      <webElementGuid>ec2126d5-907f-405a-8b89-be3bfaeb2354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]</value>
      <webElementGuid>62b542da-defe-4f12-b93b-334c65362bab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section</value>
      <webElementGuid>e10e88ce-baf8-4fb0-87c8-23071566032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[2]/following::section[1]</value>
      <webElementGuid>0b3a078a-e4ea-4a76-9d9b-8f4feb7616ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[2]/following::section[1]</value>
      <webElementGuid>35e7ea01-1cde-474c-969f-5c527bc39282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section</value>
      <webElementGuid>4c73fdab-3928-4fa5-b364-67340e364509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Modern, comprehensive quality management platformDeliver world-class digital experiences with an AI-augmented platform that lets you plan, author and execute automated tests.Get startedView a demoHelping 30K+ software, DevOps and quality teams test and launch software faster.' or . = 'Modern, comprehensive quality management platformDeliver world-class digital experiences with an AI-augmented platform that lets you plan, author and execute automated tests.Get startedView a demoHelping 30K+ software, DevOps and quality teams test and launch software faster.')]</value>
      <webElementGuid>4d1ad02e-726f-4e80-b5b8-5e0d4b8ee6be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
