<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Do not allow space_a-fce13wk0t6f5</name>
   <tag></tag>
   <elementGuidId>87a7b45b-d80c-4d75-85f7-c33997331ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-fce13wk0t6f5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-fce13wk0t6f5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b2f80b99-45db-4fc5-8a25-d89332500cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>43eaf4db-3a84-4f00-8524-91de4166bf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm&amp;co=aHR0cHM6Ly9rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=Gg72x2_SHmxi8X0BLo33HMpr&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=4hu55397b8zd</value>
      <webElementGuid>15a3bc0e-98ec-43e8-83b8-44f44877b272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>2358a45a-c8ba-420e-b77a-6ba1ee36ebc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>9bc502f4-4639-419b-8a50-f47e0f0130ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>da69a6d2-bbc1-4c74-b782-63b96326d9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-fce13wk0t6f5</value>
      <webElementGuid>e2b8798e-eb2a-4126-abf0-8eee84e3279f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a9d752a-ab9d-4c0a-9b0c-1b9654e3c59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a0852359-fe7b-4cf4-b775-b61589fe4c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>63224d07-f962-496c-935f-638282d50d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>ce499080-7b5c-4ea5-9e5f-151c1417eb28</value>
      <webElementGuid>100d7c21-2b80-4e62-8a7e-9e261761a326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;SignUp_wrapSignup__nLnnj&quot;]/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/div[4]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>753611f4-58b5-4044-945e-45736a799e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-fce13wk0t6f5']</value>
      <webElementGuid>932b4840-aa8c-4c96-99f0-ebd4a7ac82dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/div[4]/div/div/div/iframe</value>
      <webElementGuid>57c9b787-4b87-4b55-8ff9-2c4b204de3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>97d356e0-9023-4bfd-a655-7d2ca9683d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm&amp;co=aHR0cHM6Ly9rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=Gg72x2_SHmxi8X0BLo33HMpr&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=4hu55397b8zd' and @name = 'a-fce13wk0t6f5']</value>
      <webElementGuid>5d7395ec-cba8-40d7-989a-99feda4bbc3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
