<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>7b296f2d-e95a-41ed-b354-39a49e73ce58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f11ed84d-5301-45a5-a8f0-8dca40f78137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>9acbf90f-2db0-4059-8a61-0a7da42a4e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AD1IbLDFV_R6HFXsdIRxuxchpdwLuqxnmWyaYKA1zEI_L-uLf87UhhygA9DGvq_IuBEDa8T7qYgkB5A4IJprXCisfAUl1JCaGGzlBTt35sBtmwYuso5itoH0jKw5eRAmZ2WbLVnpoxDOBesXXOOPOUDm91C0mMQH3lMhbR8ypINHOrr21q_TG82cIux5MaI1zwdNlSsRDd_i&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm&amp;id=2</value>
      <webElementGuid>3827f0db-c581-4661-81e7-da29b0f39531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>96e12790-125a-47f8-807b-c5047c1ae691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign up  Katalon Software Quality Mana_03d398/iframe_html1body1div4div4iframe1_c-fce13wk0t6f5</value>
      <webElementGuid>2d992811-a955-46c8-a2fb-d53bc8ab2390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      <webElementGuid>5fd8a7b6-0e59-4ba2-aff9-c0da33789735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AD1IbLDFV_R6HFXsdIRxuxchpdwLuqxnmWyaYKA1zEI_L-uLf87UhhygA9DGvq_IuBEDa8T7qYgkB5A4IJprXCisfAUl1JCaGGzlBTt35sBtmwYuso5itoH0jKw5eRAmZ2WbLVnpoxDOBesXXOOPOUDm91C0mMQH3lMhbR8ypINHOrr21q_TG82cIux5MaI1zwdNlSsRDd_i&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm&amp;id=2')])[13]</value>
      <webElementGuid>41ae4334-b74e-4a76-aa39-d8198b71f233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/img</value>
      <webElementGuid>7f464292-1576-4183-964c-99d499876155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AD1IbLDFV_R6HFXsdIRxuxchpdwLuqxnmWyaYKA1zEI_L-uLf87UhhygA9DGvq_IuBEDa8T7qYgkB5A4IJprXCisfAUl1JCaGGzlBTt35sBtmwYuso5itoH0jKw5eRAmZ2WbLVnpoxDOBesXXOOPOUDm91C0mMQH3lMhbR8ypINHOrr21q_TG82cIux5MaI1zwdNlSsRDd_i&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm&amp;id=2']</value>
      <webElementGuid>1bf5c225-19f9-4a4d-b59d-6628e3e045f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
