<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>e33ba17e-6095-45f3-bca3-d8bd467e1404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1e0faf2-c81a-475b-bff9-9b6e2b1fab6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>67e8e976-b996-46b1-8110-4a6fddfc05ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AD1IbLDFV_R6HFXsdIRxuxchpdwLuqxnmWyaYKA1zEI_L-uLf87UhhygA9DGvq_IuBEDa8T7qYgkB5A4IJprXCisfAUl1JCaGGzlBTt35sBtmwYuso5itoH0jKw5eRAmZ2WbLVnpoxDOBesXXOOPOUDm91C0mMQH3lMhbR8ypINHOrr21q_TG82cIux5MaI1zwdNlSsRDd_i&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm</value>
      <webElementGuid>e3811d37-627a-4791-9f4d-d69acaeb3ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>704a23b6-67a9-470c-8b01-ef9abdef140e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign up  Katalon Software Quality Mana_03d398/iframe_html1body1div4div4iframe1_c-fce13wk0t6f5</value>
      <webElementGuid>10fea247-6670-49fe-9cc2-19053be90c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      <webElementGuid>ef7951ab-63e3-43c9-a22a-16fc9c451dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AD1IbLDFV_R6HFXsdIRxuxchpdwLuqxnmWyaYKA1zEI_L-uLf87UhhygA9DGvq_IuBEDa8T7qYgkB5A4IJprXCisfAUl1JCaGGzlBTt35sBtmwYuso5itoH0jKw5eRAmZ2WbLVnpoxDOBesXXOOPOUDm91C0mMQH3lMhbR8ypINHOrr21q_TG82cIux5MaI1zwdNlSsRDd_i&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm')])[13]</value>
      <webElementGuid>b034bb62-c347-4f3d-b21e-30801c111449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/img</value>
      <webElementGuid>5190ea73-d489-422b-b275-a5ed2d2401ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AD1IbLDFV_R6HFXsdIRxuxchpdwLuqxnmWyaYKA1zEI_L-uLf87UhhygA9DGvq_IuBEDa8T7qYgkB5A4IJprXCisfAUl1JCaGGzlBTt35sBtmwYuso5itoH0jKw5eRAmZ2WbLVnpoxDOBesXXOOPOUDm91C0mMQH3lMhbR8ypINHOrr21q_TG82cIux5MaI1zwdNlSsRDd_i&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm']</value>
      <webElementGuid>0ab878de-ccd3-47cd-a7bf-870254e19b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
