<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create a Katalon account_user_login</name>
   <tag></tag>
   <elementGuidId>7af40553-c33b-46b1-9e55-7bccd6c68233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signup_fullname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signup_fullname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c778ccef-3d3b-462f-a6be-8c785b5f4ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a8a03e3-59d2-4be1-965c-3aedf18c6604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_login</value>
      <webElementGuid>7c700871-8d0e-4cac-9459-55ecf42c1346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup_fullname</value>
      <webElementGuid>d24e3bea-d402-4ceb-9790-7b633f6e2c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full name</value>
      <webElementGuid>e819df4d-435b-4d71-a79f-5b9416b28ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_fullname&quot;)</value>
      <webElementGuid>59f11258-f373-4557-955e-9e4ad5713706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signup_fullname']</value>
      <webElementGuid>d6c0e4bc-d7eb-41c2-ac54-b94c37cc4abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/div/input</value>
      <webElementGuid>84bd65eb-ce40-49ea-bef6-97ef3b3c9696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>89b0e247-7666-4fb7-9111-1e676d8e21c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user_login' and @id = 'signup_fullname' and @placeholder = 'Full name']</value>
      <webElementGuid>b065d8ec-daca-47de-9b82-1f34eb52df5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
