<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do not allow space_sign-up-btn</name>
   <tag></tag>
   <elementGuidId>e7650786-aeff-419b-953a-345331bb7a3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Start testing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sign-up-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83e17322-c42b-448f-a1e3-7349aad9ae4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-up-btn</value>
      <webElementGuid>3bc3df9f-7a1b-4130-96f6-49beadddb1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5aac7d62-0850-4b62-96db-ea9c21682686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Start testing</value>
      <webElementGuid>fbbf3fc7-4db5-4784-bf8f-2d6b07126557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>cb22864b-0919-4657-ad09-3e592c7a279b</value>
      <webElementGuid>ca055a72-50d5-4803-8cb1-84098c8ef2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;SignUp_wrapSignup__nLnnj&quot;]/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/input[@class=&quot;sign-up-btn&quot;]</value>
      <webElementGuid>7fd3b6d4-d24e-408d-9708-74f618e8d451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Start testing']</value>
      <webElementGuid>dccab1ff-3166-4cc0-b763-218c84c2eb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/input</value>
      <webElementGuid>2fcd008b-82bd-4753-97a3-dae625293b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>27896e27-ca1e-47b1-8a15-3c15bec9e19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>1b344e3d-0504-419a-87c1-e8b772a9e456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
