<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valid email is required to activate p_255484</name>
   <tag></tag>
   <elementGuidId>b67eb4cd-faad-4fef-9e0d-4f657d1bd19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signup_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signup_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39567c9e-8413-4980-aeaf-bb93fb0a284a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c05842f8-491e-435b-b3ea-1a641eae14e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_pass</value>
      <webElementGuid>856a6b97-97df-4748-b63e-79f055312481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup_password</value>
      <webElementGuid>661cb2ea-d2e4-4931-a40b-6489b644abf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>b0beb7d9-1e58-4389-bafe-fba91a445688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d592ec8f-2369-41a7-9f19-4a6961258f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6e671ee3-1228-42e9-b4b5-bd53eb224981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-changed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b5479fc-a044-4314-9337-f7e782594e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_password&quot;)</value>
      <webElementGuid>f03f856f-43a3-4372-ba82-6555499788cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signup_password']</value>
      <webElementGuid>0169a8be-4dd4-4c4a-b1f7-5329fcdd37ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/div[3]/input</value>
      <webElementGuid>066f1915-1622-4b7e-8577-790fdf309025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>2bf23e51-7571-45aa-bf7e-325dd6fec407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'user_pass' and @id = 'signup_password' and @placeholder = 'Password']</value>
      <webElementGuid>66661cc9-ee4c-4b67-b33a-9e9f011f3744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
